CGM/Controllers/CGM/MapsBoundaryController.cs
using CGM.Models.CGMModels;
using CGM.Models.MyModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Serialization;
using System.Web;
using System.Web.Mvc;

namespace CGM.Controllers.CGM
{
    //[DataContract(IsReference = true)]
    public class MapsBoundaryController : Controller
    {

        private CGM_DB_Entities db = new CGM_DB_Entities(); 

        public ActionResult Index()    
        { 
            var boundary = db.Boundary.ToList();
            return View(boundary);
        }

        public JsonResult GetMD()
        {
            return Json(db.Boundary.Select(m => new MyBoundary() {
                id = m.id,
                name = m.name,
                code = m.code,
                is_active = m.is_active,
                max_active = m.max_active,
                max_reactive = (m.max_reactive == null) ? 0 : m.max_reactive,
                latitude = m.latitude, 
                longitude = m.longitude  
            }).Where(m2 => m2.longitude != null && m2.latitude != null ).ToList(), JsonRequestBehavior.AllowGet);
        } 

    }
} 

CGM/Views/MapsBoundary/Index.cshtml
@model IEnumerable<CGM.Models.CGMModels.Boundary>

@{
    Layout = "~/Views/Shared/_LayoutCGM.cshtml";
    ViewBag.Title = "Mapa de Fronteras";
}

@section styles{
    <style>
        .mapa {
            margin-top: 2em;
            margin-bottom: 2em;
        }
    </style>
}

<div class="page-header">
    <h1>MAPA DE FRONTERAS <small> </small></h1>
</div>

<div class="row">
    <div class="col-md-12 mapa">
        <div id="map" style="width:100%; height:500px;"></div>
    </div>
    <div class="col-md-12">
        <table id="table" class="table table-striped table-bordered" style="width:100%;">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.id)
                    </th>
                    <th>
                        Código
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Medida Máxima Activa
                    </th>
                    <th>
                        Medida Máxima Reactiva
                    </th>
                    <th>
                        Activo
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) 
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.max_active)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.max_reactive)
                    </td>
                    <td>
                        @if (item.is_active)
                        {
                            if (item.latitude != null && item.longitude != null)
                            {
                                <span onclick="openAllInfoWindows('@item.latitude','@item.longitude');" style="cursor:pointer">
                                    <img class="rounded float-left mr-2 mt-1" style="width:0.7em;" src="http://www.googlemapsmarkers.com/v1/A/009900/">
                                    <p>Activo</p>
                                </span>
                            }
                            else
                            {
                                <p>Activo</p>
                            }
                        }
                        else
                        {
                            if (item.latitude != null && item.longitude != null)
                            {
                                <span onclick='openAllInfoWindows(@item.latitude,@item.longitude);'>
                                    <img class="rounded float-left mr-2 mt-1" style="width:0.7em;" src="http://www.googlemapsmarkers.com/v1/I/9B9898/">
                                    <p>Inactivo</p>
                                </span>
                            }
                            else
                            {
                                <p>Inactivo</p>
                            }
                        }
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section scripts{

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8xkhgk8ADjDdy38jMpXL1gYNevyOHk0o&callback=initMap">
    </script>

    <script>

        var markers = [];

        $(function () {
            $("#table").DataTable({
                "bLengthChange": false,
                "bFilter": true,
                "bInfo": false,
                "columnDefs": [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    }
                ]
            });       

        });

        initMap = () => {
    
            const options = {
                center: {
                    lat: 1.2108156,
                    lng: -77.2824431
                },
                zoom: 13,
                mapTypeId: google.maps.MapTypeId.Hybrid
            };

            var map = document.getElementById('map');
            const mapa = new google.maps.Map(map, options);

            var iconActivo = new google.maps.MarkerImage("http://www.googlemapsmarkers.com/v1/A/009900/");
            var iconInactivo = new google.maps.MarkerImage("http://www.googlemapsmarkers.com/v1/I/9B9898/");            

            $.get("@Url.Action("GetMD", "MapsBoundary")", function (data) {

                $.each(data, function (i, item) {

                    icon = (item.is_active) ? iconActivo : iconInactivo

                    var infowindow = new google.maps.InfoWindow({
                        content: "<b>" + item.name + " </b> <br> Max Med. Activa " + item.max_active + "  <br> Max Med. Reactive " + item.max_reactive
                    });

                    var myLatlng = new google.maps.LatLng(item.latitude, item.longitude * -1);

                    var marker = new google.maps.Marker({
                        position: myLatlng,
                        title: item.name + " (" + item.max_measure_value + ")", 
                        mapTypeControl: true,
                        mapTypeControlOptions: {
                            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
                            mapTypeIds: ['roadmap', 'terrain']
                        },
                        icon: icon
                    });

                    markers.push(marker);

                    google.maps.event.addListener(marker, 'click', function () { infowindow.open(map, marker); });

                    marker.setMap(mapa);

                })

            });            
            
        };

        function openAllInfoWindows(latOp, lonOp) {
            latOp = latOp.replace(",", ".")
            lonOp = "-"+ lonOp.replace(",",".")
            for (var i = 0; i < markers.length; i++) { 
                
                let lat = intlRound(markers[i].getPosition().lat().toString());
                let lng = intlRound(markers[i].getPosition().lng().toString());
                              
                console.log(lat, latOp, lng, lonOp)

                if (lat == latOp && lng == lonOp) {
                    google.maps.event.trigger(markers[i], "click");
                    break;
                }
            }
        }

        function intlRound(numero, decimales = 6, usarComa = false) {
            var opciones = {
                maximumFractionDigits: decimales,
                useGrouping: false
            };
            usarComa = usarComa ? "es" : "en";
            return new Intl.NumberFormat(usarComa, opciones).format(numero);
        }

    </script>
}