CGM/Models/CGMModels/Report_Type.cs
namespace CGM.Models.CGMModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Report_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        [Column("report_type")]
        [DisplayName("Negocio")]
        [StringLength(20)]
        public string report_type1 { get; set; }

        [StringLength(100)]
        public string path { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boundary> Boundary { get; set; }

    }
}

CGM/Models/MyModels/ReportViewModel.cs
using CGM.Models.CGMModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CGM.Models.MyModels
{
    public class ReportViewModel
    {
        public List<VMeasure> listToReport { get; set; }
        public List<VCurvaTipMeasure> listCurvaTips { get; set; }
        public List<Boundary> listNoActive { get; set; }
        public List<Boundary> listNoData { get; set; }
    }
}

CGM/Controllers/CGM/ReportsController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CGM.Models.CGMModels;
using CGM.Helpers;
using System.IO;
using CGM.Models.MyModels;
using System.Globalization;
using System.Threading.Tasks;
using CGM.Helpers.Attributes;
using NLog;
using System;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using CGM.Areas.Telemetry.Models;

namespace CGM.Controllers.CGM
{
    public class ReportsController : Controller
    {

        private static Logger logger = LogManager.GetCurrentClassLogger();
        private CGM_DB_Entities db = new CGM_DB_Entities();
        NumberFormatInfo provider = new NumberFormatInfo { NumberDecimalSeparator = "." };
        private static List<VMeasure> listToReport;
        private static int[] currentBoundaryIds;
        private static List<Boundary> boundaries; //Se hace un objeto estático, pues se hace esta petición varias veces a la base de datos.
        private static int report_id;
        private static List<VMeasure> vMeasures;
        private static DateTime fecha;
        private static int negocio;
        private static string fileName;
        // GET: Reports
        [CustomAuthorize(Roles = "Desarrollador,Administrador")]
        public ActionResult Index()
        {
            List<Report> reports = db.Reports.ToList();
            ViewBag.Result = TempData["result"];
            ViewBag.navbar1 = "Reportes";
            return View(reports);
        }

        [CustomAuthorize(Roles = "Desarrollador,Administrador")]
        public ActionResult Manual()
        {
            ViewBag.Result = TempData["result"];

            boundaries = db.Boundary.ToList();

            var quantitiesDB = db.Quantity.Include(q => q.Magnitude).Where(q => q.name == "Energía Reactiva Positiva" || q.name == "Energía Activa (Positiva)").ToList();

            ViewBag.quantity_id = new SelectList(quantitiesDB, "id", "name", 1);

            return View(boundaries);
        }

        public ActionResult GetPreReport(string ids, int report_type, string opday, int quantity_id, string criticParameters, int curvaTipId = 0)
        {
            DateTime dt = DateTime.Parse(opday);
            int[] boundariesids = ids.Split(',').Select(int.Parse).ToArray();

            listToReport = MarketReport.getMeasuresReport(boundariesids, dt, quantity_id);//report_type);

            currentBoundaryIds = listToReport.Select(v => v.id).Distinct().ToArray();

            List<Boundary> listNoActive = boundaries.Where(b => b.report_type_id == report_type && b.is_active == false).ToList();
            List<Boundary> listNoData = boundaries.Where(b => !listToReport.Any(lr => lr.id == b.id) && b.is_active).ToList(); //Se toma las fronteras que no registran datos. Que no están en el reporte.
            //List<VCurvaTipMeasure> ctm = ;
            List<VCurvaTipMeasure> listCurvaTips = new List<VCurvaTipMeasure>();

            int curvaTipSelected = 0;

            if (curvaTipId != 0)
           {
                listCurvaTips = db.VCurvaTipMeasures.AsNoTracking().Where(c => c.id == curvaTipId && currentBoundaryIds.Contains(c.id_boundary)).ToList();
                curvaTipSelected = curvaTipId;
            }
            else
            {
                // Select the CurvaTip set by default
                var curvaTipDefault = db.CurvaTip.Where(c => c.Acquisition_Item.quantity_id == quantity_id
                                                          && c.Acquisition_Item.tag_line_id == 4 // TagLine = 4 => Total. Assume that in the report Total measurements are taken
                                                          && c.isDefault).FirstOrDefault();

                if (curvaTipDefault != null)
                {
                    curvaTipSelected = curvaTipDefault.id;
                }
            }
            

            ViewBag.CurvaTipsSelection = curvaTipId;
            string negocio = report_type == 0 ? "25" : "26"; // "25"= Generación; "26" = Comercialización
            string[] splitDate = dt.ToString().Split('/');
            fileName = "CR" + negocio + splitDate[1] + splitDate[0];
            ViewBag.fileName = fileName;

            var curvatips = db.CurvaTip.ToList();

            ViewBag.curvaTipSelector = new SelectList(db.CurvaTip, "id", "name", curvaTipSelected);

            ReportViewModel rvm = new ReportViewModel()
            {
                listNoActive = listNoActive,
                listNoData = listNoData,
                listToReport = listToReport,
                listCurvaTips = listCurvaTips
            };

            if (listToReport.Count != 0)
            {
                ViewBag.min = listToReport.Min(m => m.measure);
                ViewBag.max = listToReport.Max(m => m.measure);
            }

            // Default form configuration is in json form already
            ViewBag.defaultFormConfig = db.Config_CM.Where(c => c.element.Trim().Equals("defaultParametersVisualConfig")).FirstOrDefault().text;

            return PartialView("_Prereport", rvm);
        }

        /// <summary>
        /// Se ejecuta después de haber generado la primera vista de reporte, pues usa el objeto listToReport, y remplaza la tabla original
        /// con la tabla con la crítica. Esto es, el análiis de las medidas dependiendo de unos valores de comparación.
        /// </summary>
        /// <returns></returns>
        public ActionResult GetCurvaTipCriticTable(string ids, int report_type, string opday, int quantity_id, string criticParameters, int curvaTipId = 0)
        {
            List<CriticBoundary> criticBoundaries = new List<CriticBoundary>();
            if (opday == null || opday == "" || curvaTipId == 0 || criticParameters == "" || criticParameters == null ) // Safety check
            {
                ViewBag.Result = new KeyValuePair<string, string>("warning", "Parámetros incompletos, o no se encuentra datos para la solicitud.");
                return PartialView("~/Measures/_Critic.cshtml", criticBoundaries);
            }

            DateTime dt = DateTime.Parse(opday);
            // Varios de los parámetros enviados son inicializados en la solicitud inicial del reporte, en GetPreReport
            if (currentBoundaryIds == null) // En caso de que no se recargue la página o algo. Esto no debería presentarse. Sólo en caso.
            {
                currentBoundaryIds = ids.Split(',').Select(int.Parse).ToArray(); // Posiblemente se agreguen más fronteras de las que se están analizando. 
            }

            // Get the Acquisition item corresponding to that quantity in the particular case of Total measurements (ta_line_id == 4)
            int acq_item_id = db.Acquisition_Item.Where(a => a.quantity_id == quantity_id && a.tag_line_id == 4).Select(a => a.Id).FirstOrDefault();

            // Remove Critic For Boundaries with Alumbrado Público. No sense in doing critics to that
            int[] boundariesAP_ids = db.Boundary.Where(b => b.Boundary_Source.source == "Alumbrado Público" && currentBoundaryIds.Contains(b.id)).Select(b => b.id).ToArray();
            currentBoundaryIds = currentBoundaryIds.Except(boundariesAP_ids).ToArray();

            var measuresToCritic = listToReport.Where(m => currentBoundaryIds.Contains(m.id)).ToList();

            CriticSummary criticSummary = CriticController.GetCriticInReport(currentBoundaryIds, dt, acq_item_id, curvaTipId, criticParameters, measuresToCritic);

            

            // Get the quantity (mainly for display)
            Quantity quantity = db.Quantity.Include(q => q.Magnitude).Where(q => q.id == quantity_id).FirstOrDefault(); 
            ViewBag.quantity_name = quantity.name;
            ViewBag.quantity_unit = quantity.Magnitude.unit_symbol;

            // Put the data in the rigght javascript format to display in the chart
            Dictionary<string, List<double[]>> chartData = CriticController.ChartData(criticSummary.boundaries);
            ViewBag.chartData = JsonConvert.SerializeObject(chartData);
            ViewBag.criticSummary = JsonConvert.SerializeObject(criticSummary);

            if (listToReport.Count != 0)
            {
                ViewBag.min = listToReport.Min(m => m.measure);
                ViewBag.max = listToReport.Max(m => m.measure);
            }
            ViewBag.fileName = fileName;
            ViewBag.curvaTipName = db.CurvaTip.Find(curvaTipId).name;



            return PartialView("~/Views/Critic/_Critic.cshtml", criticSummary);
        }

        public ActionResult SendReportResult()
        {
             return View("Details", db.Reports.Include(r => r.Report_Informs.Select(ri => ri.Boundary))
                                              .Include(r => r.Report_Informs.Select(ri => ri.Substatus))
                                              .Include(r => r.Report_Type)
                                              .FirstOrDefault(r => r.id == report_id));
        }
        public ActionResult Details(int id)
        {
            return View("Details", db.Reports.Include(r => r.Report_Informs.Select(ri => ri.Boundary)).Include(r => r.Report_Type).FirstOrDefault(r => r.id == id));
        }
        public ActionResult SendReport()
        {
            List<VBoundary> vBoundaries = VBoundary.ToVBoundaries(listToReport);
            MarketReport mr = new MarketReport();
            Tuple<string, Report> res = mr.ReportToMarket(vBoundaries);

            if (res.Item2 != null) //No hubo errores y se devolvió un objeto
            {
                report_id = res.Item2.id;
                return RedirectToAction("SendReportResult");
            }
            else
            {
                TempData["result"] = new KeyValuePair<string, string>("error", res.Item1);

                return RedirectToAction("Manual");
            }
        }
        [CustomAuthorize(Roles = "Desarrollador,Administrador")]

CGM/Views/Reports/Details.cshtml
@model CGM.Models.CGMModels.Report
@ViewHelpers.NavBar("Mercado", "Reporte manual", Url.Content("~"))

@{
    ViewBag.Title = "Detalles de reporte";
    Layout = "~/Views/Shared/_LayoutCGM.cshtml";
}

<header>
    <h2>Detalles del reporte</h2>
</header>

<div class="row">
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <h5>Resumen</h5>
            </div>
            <div class="card-body">
                <table class="table">
                    <tr><td>Negocio</td><td>@Model.Report_Type.report_type1</td></tr>
                    <tr><td>Día de operación</td><td>@Model.operation_date.Value.ToLongDateString()</td></tr>
                    <tr><td>Fronteras reportadas</td><td>@Model.Report_Informs.GroupBy(ri => ri.boundary_id.Value).Count()</td></tr>
                    <tr><td>Registros totales</td><td>@Model.Report_Informs.Count</td></tr>
                    <tr><td>Resultado</td><td><h4>@ViewHelpers.StatusResult(Model.status_id)</h4></td></tr>
                    <tr><td>Identificador</td><td>@Model.external_report_id</td></tr>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <h5>Detalle de resultados</h5>
            </div>
            <div class="card-body">
                @if (Model != null)
                {
                    <div class="table-responsive">
                        <table id="tblResults" class="table table-sm small">
                            <thead>
                                <tr>
                                    <th>Frontera</th>
                                    <th>Código</th>
                                    <th>Tipo</th>
                                    <th>Estado</th>
                                    <th>Mensaje</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var ri in Model.Report_Informs)
                                {
                                    <tr>
                                        <td>@ri.Boundary.name</td>
                                        <td>@ri.Boundary.code</td>
                                        <td>@ViewHelpers.IsBackup(ri.is_backup.Value)</td>
                                        <td><strong>@ViewHelpers.StatusResult(ri.Substatus.idStatus)</strong></td>
                                        <td>@ri.message</td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    @ViewHelpers.NoElements()
                }
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        $('#tblResults').DataTable(
            {
                "language": {
                    "url": "@Url.Content("~")Scripts/es-CO.txt"
                 }
            })
        //table.columns.adjust().draw()
    })
</script>
@section scriptsbody
{
    @Scripts.Render("~/bundles/dataTablesScript")
}
@section styles{
    <!-- Datatables stylesheet-->
    @Styles.Render("~/bundles/dataTablesStyle")
}

CGM/Views/Reports/Index.cshtml
@model IEnumerable<CGM.Models.CGMModels.Report>

@{
    String ctrl = ViewBag.ControllerName;
    var modelName = "tbl_" + ctrl;
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutCGM.cshtml";
}


<header>
    <div class="row">
        <div class="col-lg-6">
            <h1 class="display">
                Index
            </h1>
        </div>
        <div class="col-lg-6 text-right">
            <div class="btn-group">
                @Html.ActionLink("+ Añadir nuevo elemento", "Create", null, new { @class = "btn btn-primary", data_toggle = "tooltip", data_placement = "top", title = "Agregar elemento" })
            </div>
        </div>
    </div>
</header>


<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div>
                <div class="card-header">
                    <h2> Listado</h2>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="@modelName" class="table">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Acquisition.Name)</th>
                                <th>@Html.DisplayNameFor(model => model.AspNetUsers.Email)</th>
                                <th>@Html.DisplayNameFor(model => model.Destination.name)</th>
                                <th>@Html.DisplayNameFor(model => model.Program.name)</th>
                                <th>@Html.DisplayNameFor(model => model.Report_Type.report_type1)</th>
                                <th>@Html.DisplayNameFor(model => model.Status.name)</th>
                                <th>@Html.DisplayNameFor(model => model.date_and_time_to_report)</th>
                                <th>@Html.DisplayNameFor(model => model.date_and_time_to_report_end)</th>
                                <th>@Html.DisplayNameFor(model => model.date_and_time_report)</th>
                                <th>@Html.DisplayNameFor(model => model.is_active)</th>
                                <th>@Html.DisplayNameFor(model => model.time_elapsed)</th>
                                <th>@Html.DisplayNameFor(model => model.is_auto)</th>
                                <th>@Html.DisplayNameFor(model => model.external_report_id)</th>
                                <th>@Html.DisplayNameFor(model => model.operation_date)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Acquisition.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.AspNetUsers.Email)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Destination.name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Program.name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.operation_date)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Report_Type.report_type1)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Status.name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.date_and_time_to_report)</td>
                                    <td>@Html.DisplayFor(modelItem => item.date_and_time_to_report_end)</td>
                                    <td>@Html.DisplayFor(modelItem => item.date_and_time_report)</td>
                                    <td>@Html.DisplayFor(modelItem => item.is_active)</td>
                                    <td>@Html.DisplayFor(modelItem => item.time_elapsed)</td>
                                    <td>@Html.DisplayFor(modelItem => item.is_auto)</td>
                                    <td>@Html.DisplayFor(modelItem => item.external_report_id)</td>
                                    <td>@Html.ActionLink(" ", "Details", new { id = item.id, }, new { @class = "fa fa-list", data_toggle = "tooltip", data_hint_background = "bg-blue", data_placement = "top", title = "Detalles" }) &nbsp;</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section scriptsbody{
    @Scripts.Render("~/bundles/dataTablesScript")
    <script>
        $(document).ready(function () {
            $('#@modelName').DataTable(
                    {
                    "language": {
                        "url": "../Scripts/es-CO.txt"
                    }
                }
            );
        });
    </script>
}

@section styles{
    <!-- Datatables stylesheet-->
    @Styles.Render("~/bundles/dataTablesStyle")
}

CGM/Views/Reports/LoadFile.cshtml
@{
    ViewBag.Title = "Carga de medidas";
    Layout = "~/Views/Shared/_LayoutCGM.cshtml";
}


<div class="container-fluid">
    <!-- Page Header-->
    <header>
        <h1>Carga de Archivos</h1>
    </header>
    @Html.Partial("_TempResult")

    <div class="row">
        <div class="col-xl-6">
            <div class="card">
                <div class="card-header">
                    <h4>Medidas en archivo plano</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <span>
                                Puede cargar información de medidas manualmente hacia la base de datos, por medio del formato utilizado en versiones anteriores de reportes.
                                Para ver la descripción del formato, haga clic
                                <a class="text-primary" id="formato" href="#">aquí.</a>
                            </span>
                        </div>
                        <div class="col-md-6">
                            <form class="dropzone dz-clickable" id="fileUpload" action="@Url.Content("~")Reports/LoadFilePost">
                                <div class="dz-message">
                                    <p>Arrastre el archivo hasta aquí.</p>
                                </div>
                            </form>
                        </div>
                    </div>
                    <br />
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-12">
        <div id="LoadResult">
        </div>
    </div>
</div>

@section scriptsbody{
    <!-- Dropzone.js-->
    <script src="~/Content/vendor/dropzone/dropzone.js"></script>
    <!-- Dropzone Init-->
    <script src="~/Content/js/forms-dropzone.js?v=0.4"></script>

    @*El archivo forms-dropzone está bastante editado por mí*@

    @Scripts.Render("~/bundles/dataTablesScript")

    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.colVis.min.js"></script>
}

@section styles{
    @Styles.Render("~/bundles/dataTablesStyle")
    <link href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.bootstrap4.min.css" rel="stylesheet" />
}

CGM/Views/Reports/_Tabla_Medidas.cshtml
@model CGM.Models.MyModels.ReportElementSet

@if (Model != null)
{
    if (Model.reportElements.Count > 0)
    {
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-3">
                        <p><h3>Fecha</h3></p> <h3>@Model.dateReport.ToShortDateString()</h3>
                    </div>
                    <div class="col-sm-3">
                        <p><h3>Unidad de Negocio</h3></p>
                        @if (Model.negocio == 0)
                        {
                            <h3>Generación</h3>
                        }
                        @if (Model.negocio == 1)
                        {
                            <h3>Comercialización</h3>
                        }
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table TableData" style="background-color:white">
                    <thead>
                        <tr>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Código
                            </th>
                            <th>
                                Tipo
                            </th>
                            @for (int i = 1; i <= 24; i++)
                            {
                                <th style="text-align:center">
                                    @String.Format("h{0}", i)
                                </th>
                            }
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.reportElements)
                        {
                            <tr>
                                <th>
                                    @item.boundary.name
                                </th>
                                <th>
                                    @item.boundary.code
                                </th>
                                @if (@item.isBackup == true)
                                {
                                    <th>R</th>
                                }
                                else
                                {
                                    <th>P</th>

                                }

                                @foreach (var medida in item.measures)
                                {
                                    <th>@Math.Round(medida.measure1, 2)</th>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <span style="width:100%">
            @*<button class="btn btn-success" onclick="cargarMedidas()" style="margin:20px;"><i class="fa fa-upload"></i> Cargar medidas </button>*@
            <button id="btnLoad" class="btn btn-success ladda-button" data-style="zoom-in" style="margin:20px;"><i class="fa fa-upload"></i> Cargar medidas </button>

        </span>
    }
}
else
{
    <div class="row"><h4>Validación fallida.</h4></div>
    <div class="row">
        <div class="col-lg-12"><h4 class="alert alert-warning"><i class="fa fa-warning" />  @ViewBag.Error </h4></div>
    </div>
}

<div class="modal fade" id="msgModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div></div>
        </div>
    </div>
</div>
<script>

    $("#btnLoad").click(function () {
        console.log("qué pasa che!")
        location.href = "@Url.Action("UploadDataFromFile","Reports",null)";
    })

    function cargarMedidas() { //Función tomada parcialmente de la solución de Survey. Esta función se la uso al principio, pero ya no se hace una llamada desde Ajax, sino directamente al controlador
        xcn = sessionStorage.getItem('token_type') + ' ' + sessionStorage.getItem('access_token');
        $.ajax({
            type: "GET",
            url: "@Url.Content("~")api/Reports/UploadDataFromFile",
            contentType: false,
            processData: false,
            data: null,
            headers: {
                'Authorization': 'bearer ' + sessionStorage.getItem('access_token')
            },
            /*data.__RequestVerificationToken = $('#__AjaxAntiForgeryForm input[name=__RequestVerificationToken]').val()*/

            success: function (data) {
                console.log(data);
            }
        });
        console.log("Pasó Ajax");

}
</script>

CGM/Views/Reports/_Tabla_vMedidas.cshtml
@model IEnumerable<CGM.Models.CGMModels.VMeasure>
@{ int cont = 0; string buffer = "";}

@if (Model != null)
{
    <div class="card">
        <div class="card-body">
            @if (Model.Count() != 0)
            {
                <div class="table-responsive">
                    <table id="tblBoundaries" class="table small">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Código</th>
                                <th style="padding-right: 180px">Frontera</th>
                                <th>P/R</th>
                                <th>H0</th>
                                @for (int i = 1; i <= 24; i++)
                                {
                                    <th>H@(i)</th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var boundary in Model.GroupBy(m => new Tuple<string, string, bool?>(m.name, m.code, m.is_backup)).OrderBy(g => g.Key.Item1))
                            {
                                if (boundary.Key.Item1 != buffer) { cont++; buffer = boundary.Key.Item1; }

                                <tr>
                                    <td>@cont</td>
                                    <td>@Html.DisplayFor(model => boundary.Key.Item2)</td>
                                    <td>@Html.DisplayFor(model => boundary.Key.Item1)</td>
                                    <td>@ViewHelpers.backupHelperSimple(boundary.Key.Item3)</td>
                                    <td>0</td>
                                    @foreach (var measure in boundary.OrderBy(m => m.hour))
                                    {
                                        <td class="text-center">@Math.Round(@measure.measure, 3).ToString().Replace(',', '.')</td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <hr />

                if (cont == 1)
                {<p><strong>Total: @cont Frontera</strong></p>}
            else
            {<p><strong>Total: @cont Fronteras</strong></p>}

        <span style="width:100%">
            @*<button class="btn btn-success" onclick="cargarMedidas()" style="margin:20px;"><i class="fa fa-upload"></i> Cargar medidas </button>*@
            <button id="btnLoad" class="btn btn-success ladda-button" data-style="zoom-in" style="margin:20px;"><i class="fa fa-upload"></i> Cargar medidas </button>

        </span>
        <script>

            //renderReportTable(@ViewBag.min.ToString().Replace(',','.'),@ViewBag.max.ToString().Replace(',', '.'), "@Url.Content("~")Scripts/es-CO.txt", "@ViewBag.fileName")

        </script>

    }
    else
    {
        @ViewHelpers.NoElements()
    }
        </div>
    </div>
}
else
{
    <div class="row"><h4>Validación fallida.</h4></div>
    @Html.Partial("_TempResult")
}
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title" id="exampleModalCenterTitle">Confirmación</h1>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Confirma enviar la información de este reporte?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                @Html.ActionLink("Aceptar", "SendReport", "Reports", null, new { @class = "btn btn-block btn-warning", id = "btnSend" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#btnSend').click(function myfunction() {
            $(this).attr('disable', 'disable')
    })

    $("#btnLoad").click(function () {
        console.log("qué pasa che!")
        location.href = "@Url.Action("UploadDataFromFile","Reports",null)";
    })


</script>